
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.sistemasoperativos.pcvirtual.compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int JNE = 16;
  public static final int INT = 12;
  public static final int AX = 20;
  public static final int DX = 23;
  public static final int INT10H = 26;
  public static final int SEPARATOR = 2;
  public static final int POP = 19;
  public static final int JMP = 13;
  public static final int SUB = 8;
  public static final int INT_LITERAL = 28;
  public static final int INC = 9;
  public static final int COMMA = 3;
  public static final int EOF = 0;
  public static final int CMP = 14;
  public static final int BX = 21;
  public static final int PUSH = 18;
  public static final int ADD = 7;
  public static final int MOV = 6;
  public static final int DEC = 10;
  public static final int AC = 24;
  public static final int LOAD = 4;
  public static final int error = 1;
  public static final int JE = 15;
  public static final int INT09H = 27;
  public static final int INT20H = 25;
  public static final int STORE = 5;
  public static final int PARAM = 17;
  public static final int SWAP = 11;
  public static final int CX = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEPARATOR",
  "COMMA",
  "LOAD",
  "STORE",
  "MOV",
  "ADD",
  "SUB",
  "INC",
  "DEC",
  "SWAP",
  "INT",
  "JMP",
  "CMP",
  "JE",
  "JNE",
  "PARAM",
  "PUSH",
  "POP",
  "AX",
  "BX",
  "CX",
  "DX",
  "AC",
  "INT20H",
  "INT10H",
  "INT09H",
  "INT_LITERAL"
  };
}

